export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
export const FETCH_ALL_EMPLOYEES = "FETCH_ALL_EMPLOYEES";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const FETCH_EMPLOYEE = "FETCH_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DEPARTMENTS = ["All", "Finanace", "Marketing", "HR"];
export const TOGGLE_ADMIN = "TOGGLE_ADMIN";
